name: Code Owner Enforcement

# Updated to use the fixed upstream action tmbtech/multi-codeowners@v1.0.1
# which resolves the bundling issue reported in tmbtech/multi-codeowners#2

on:
  pull_request:
    types: [opened, synchronize, ready_for_review]
  pull_request_review:
    types: [submitted, dismissed]

permissions:
  contents: read
  pull-requests: write
  checks: write
  issues: write

jobs:
  code-owners-check:
    name: Check Code Owners Approvals
    runs-on: ubuntu-latest
    
    # Skip draft PRs and if labeled to skip
    if: >-
      github.event.pull_request.draft == false &&
      !contains(github.event.pull_request.labels.*.name, 'skip-owners-check')
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Run multi-codeowners enforcement
        uses: tmbtech/multi-codeowners@v1.0.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Comment on success
        if: success()
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '🎉 **All required code owners have approved this PR!** ✅\n\nThis PR can now be merged safely.'
            });
